### PR TITLE
fix: Eliminate S3 bucket deprecation warnings in infrastructure code

### LINKED ISSUE #17079: Infra code gets deprecation warnings in pulumi CLI output
When deploying (GitHub build & deploy actions), the infra code throws the following warnings due to deprecated resources.

```output
@ Previewing update....
    pulumi:pulumi:Stack www.pulumi.com-www-testing running 
@ Previewing update........
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/guides/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/registry/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/pulumi-ai-app-infra/prod
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/guides/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/registry/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/pulumi-ai-app-infra/prod
@ Previewing update......
 ~  pulumi:providers:aws usEast1 update [diff: ~version]
    aws:s3:Bucket bundles-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket bundles-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket bundles-bucket  [diff: ~provider]; warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket uploads-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket uploads-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
    aws:s3:Bucket uploads-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
    aws:s3:Bucket uploads-bucket  [diff: ~provider]; warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
 ++ aws:s3:BucketPolicy origin-bucket-policy create replacement [diff: ~bucket,policy]
 +- aws:s3:BucketPolicy origin-bucket-policy replace [diff: ~bucket,policy]
@ Previewing update....
 ~  aws:lambda:Function answers-rewrites-lambdaEdge update [diff: ~code,lastModified,qualifiedArn,qualifiedInvokeArn,version]
 ~  aws:cloudfront:Distribution cdn update [diff: ~defaultCacheBehavior,orderedCacheBehaviors,origins]
@ Previewing update.....
 -- aws:s3:BucketPolicy origin-bucket-policy delete original [diff: ~bucket,policy]
    pulumi:pulumi:Stack www.pulumi.com-www-testing  
Policies:
    ⚠️ pulumi-internal-policies@v0.0.6
        - [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: bundles-bucket)
          Encourages use of cross-region replication for S3 buckets.
          S3 buckets should have cross-region replication.
        - [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: uploads-bucket)
          Encourages use of cross-region replication for S3 buckets.
          S3 buckets should have cross-region replication.
        - [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: website-logs-bucket)
          Encourages use of cross-region replication for S3 buckets.
          S3 buckets should have cross-region replication.
Diagnostics:
  aws:s3:Bucket (uploads-bucket):
    warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
  aws:s3:Bucket (bundles-bucket):
    warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    [Pulumi Neo] Would you like help with these diagnostics?
    https://app.pulumi.com/pulumi/www.pulumi.com/www-testing/previews/bb21bff5-bef9-470e-a9e9-74baae969e0e?explainFailure
Outputs:
  ~ originBucketName           : "www-testing-pulumi-docs-origin-push-c5000f77" => "www-testing-pulumi-docs-origin-workflow-dispatch-13be448d"
  ~ originBucketWebsiteEndpoint: "www-testing-pulumi-docs-origin-push-c5000f77.s3-website-us-west-2.amazonaws.com" => "www-testing-pulumi-docs-origin-workflow-dispatch-13be448d.s3-website-us-west-2.amazonaws.com"
  ~ originS3BucketName         : "www-testing-pulumi-docs-origin-push-c5000f77" => "www-testing-pulumi-docs-origin-workflow-dispatch-13be448d"
Resources:
    ~ 3 to update
    +-1 to replace
    4 changes. 21 unchanged
Updating (pulumi/www-testing)
View Live: https://app.pulumi.com/pulumi/www.pulumi.com/www-testing/updates/1682
Loading policy packs...
@ Updating....
@ Updating.....
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/guides/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/registry/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/pulumi-ai-app-infra/prod
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/guides/testing
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/registry/testing
@ Updating....
    pulumi:pulumi:Stack www.pulumi.com-www-testing running read pulumi:pulumi:StackReference pulumi/pulumi-ai-app-infra/prod
@ Updating......
 ~  pulumi:providers:aws usEast1 updating (0s) [diff: ~version]
    aws:s3:Bucket bundles-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket bundles-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket bundles-bucket  [diff: ~provider]; warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket uploads-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    aws:s3:Bucket uploads-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
    aws:s3:Bucket uploads-bucket  warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
    aws:s3:Bucket uploads-bucket  [diff: ~provider]; warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
 ++ aws:s3:BucketPolicy origin-bucket-policy creating replacement (0s) [diff: ~bucket,policy]
 ~  pulumi:providers:aws usEast1 updated (0.10s) [diff: ~version]
@ Updating....
 ++ aws:s3:BucketPolicy origin-bucket-policy created replacement (0.82s) [diff: ~bucket,policy]
 +- aws:s3:BucketPolicy origin-bucket-policy replacing (0s) [diff: ~bucket,policy]
 +- aws:s3:BucketPolicy origin-bucket-policy replaced (0.00s) [diff: ~bucket,policy]
 ~  aws:lambda:Function answers-rewrites-lambdaEdge updating (0s) [diff: ~code,lastModified,qualifiedArn,qualifiedInvokeArn,version]
@ Updating...............
 ~  aws:lambda:Function answers-rewrites-lambdaEdge updated (11s) [diff: ~code,lastModified,qualifiedArn,qualifiedInvokeArn,version]
 ~  aws:cloudfront:Distribution cdn updating (0s) [diff: ~defaultCacheBehavior,orderedCacheBehaviors,origins]
@ Updating......................................................................................................................................
 ~  aws:cloudfront:Distribution cdn updated (131s) [diff: ~defaultCacheBehavior,orderedCacheBehaviors,origins]
@ Updating.....
 -- aws:s3:BucketPolicy origin-bucket-policy deleting original (0s) [diff: ~bucket,policy]
@ Updating....
 -- aws:s3:BucketPolicy origin-bucket-policy deleted original (0.43s) [diff: ~bucket,policy]
    pulumi:pulumi:Stack www.pulumi.com-www-testing  
Policies:
    ⚠️ pulumi-internal-policies@v0.0.6
        - [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: bundles-bucket)
          Encourages use of cross-region replication for S3 buckets.
          S3 buckets should have cross-region replication.
        - [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: uploads-bucket)
          Encourages use of cross-region replication for S3 buckets.
          S3 buckets should have cross-region replication.
        - [advisory]  s3-bucket-replication-enabled  (aws:s3/bucket:Bucket: website-logs-bucket)
          Encourages use of cross-region replication for S3 buckets.
          S3 buckets should have cross-region replication.
Diagnostics:
  aws:s3:Bucket (bundles-bucket):
    warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::bundles-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
  aws:s3:Bucket (uploads-bucket):
    warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: website is deprecated. Use the aws_s3_bucket_website_configuration resource instead.
    warning: urn:pulumi:www-testing::www.pulumi.com::aws:s3/bucket:Bucket::uploads-bucket verification warning: cors_rule is deprecated. Use the aws_s3_bucket_cors_configuration resource instead.
    [Pulumi Neo] Would you like help with these diagnostics?
    https://app.pulumi.com/pulumi/www.pulumi.com/www-testing/updates/1682?explainFailure
Outputs:
    cloudFrontDomain           : "d298m5mqqr8wsc.cloudfront.net"
  ~ originBucketName           : "www-testing-pulumi-docs-origin-push-c5000f77" => "www-testing-pulumi-docs-origin-workflow-dispatch-13be448d"
    originBucketWebsiteDomain  : "s3-website-us-west-2.amazonaws.com"
  ~ originBucketWebsiteEndpoint: "www-testing-pulumi-docs-origin-push-c5000f77.s3-website-us-west-2.amazonaws.com" => "www-testing-pulumi-docs-origin-workflow-dispatch-13be448d.s3-website-us-west-2.amazonaws.com"
  ~ originS3BucketName         : "www-testing-pulumi-docs-origin-push-c5000f77" => "www-testing-pulumi-docs-origin-workflow-dispatch-13be448d"
    readme                     : "# Stack README\n\nThis README documents the infrastructure for the Pulumi Website which encompasses the following areas:\n..."
    uploadsBucketName          : "uploads-bucket-3f7b61a"
    websiteDomain              : "www.pulumi-test.io"
Resources:
    ~ 3 updated
    +-1 replaced
    4 changes. 21 unchanged
Duration: 2m33s
```

### PR DESCRIPTION
**Pull request by CamSoper**
Fixes #17079

Removes deprecated \`website\` and \`corsRules\` properties from S3 bucket 
resources and replaces them with separate \`BucketWebsiteConfiguration\` 
and \`BucketCorsConfiguration\` resources per AWS provider v7.0+ best practices.

## Changes
- Refactored \`uploadsBucket\` to use \`BucketWebsiteConfiguration\` and \`BucketCorsConfiguration\`
- Refactored \`bundlesBucket\` to use \`BucketWebsiteConfiguration\`
- Refactored \`fallbackBucket\` to use \`BucketWebsiteConfiguration\`
- Updated CloudFront origin to reference new website configuration resource

This eliminates deprecation warnings during infrastructure deployments 
while maintaining full backward compatibility.

**This has been successfully deployed and tested on `pulumi-test.io`.** [Build details](https://github.com/pulumi/docs/actions/runs/21876210011/job/63145698295)

### CODE REVIEW

File: infrastructure/index.ts [hunk 1]
```diff
@@ -197,9 +206,20 @@ if (config.makeFallbackBucket) {
...
-            website: {
-                indexDocument: "index.html",
-                errorDocument: "404.html",
+        },
+        {
+            protect: true,
+        },
+    );
+
+    const fallbackBucketWebsite = new aws.s3.BucketWebsiteConfiguration(
```
[the remark this answers is not in the document]
Comment (CamSoper) [reply infrastructure/index.ts:215]: That's a nit.

File: infrastructure/index.ts [hunk 2]
```diff
@@ -197,9 +206,20 @@ if (config.makeFallbackBucket) {
         "fallback-bucket", {
             bucket: config.websiteDomain,
             acl: aws.s3.CannedAcl.PublicRead,
-            website: {
-                indexDocument: "index.html",
-                errorDocument: "404.html",
+        },
+        {
+            protect: true,
+        },
```
Comment (cnunciato) [inline infrastructure/index.ts:212]: We don't seem to have this now. Is it something we should've had all along? 

I guess the meta-question is whether we really need this bucket, and if we do, how to use it. I _think_ we may have created it in response to a CloudFront outage years ago to give us something to push to in an emergency — the idea being that we could push to this bucket and click-ops a Route 53 change to point to the bucket directly if we had to. But I don't think we actually push anything to it today (at least not in CI), and I'm not sure anyone would know that this is here and what to do with it if we did have an outage.

So while the param is probably fine, it'd probably be worth a little follow-up work and/or documentation to make use of this. What do you think?

Comment (CamSoper) [reply infrastructure/index.ts:212]: Innnnteresting. I just assumed it had a purpose, but if we're not using it, maybe we should retire it. That said, I'll do it as a separate PR so as to minimize blast radius.
