### PR TITLE
Run the broken-link checker using a local website build

### LINKED ISSUE #2709: Travis CRON jobs are failing often
Many Travis CRON jobs have recently started failing due to `hugo server` OOMing:

https://travis-ci.com/github/pulumi/docs/builds/154411399

```
371make validate
372make[1]: Entering directory '/home/travis/build/pulumi/docs'
373hugo server \
374    --buildDrafts --disableBrowserError --disableLiveReload \
375    &>/dev/null &
376while ! nc -z localhost 1313; do sleep 0.1; done
377Building sites … fatal error: runtime: out of memory
```

Since we’re no longer running the broken link checker against PRs, should we consider making it so that the CRON job checks for broken links against the actual deployed www.pulumi.com itself, rather than using Hugo's built-in webserver?

Or are there any other knobs to `hugo server` we could add to help prevent it from OOMing?

Another option would be to explore upgrading Hugo to a more recent version, which might not OOM as much?

Or can we get more memory to use during Travis jobs?

@cnunciato, do you have any cycles to look into this?

### PR DESCRIPTION
**Pull request by cnunciato**
Fixes #2709.

### CODE REVIEW

File: scripts/check-links.sh [hunk 1]
```diff
@@ -49,4 +51,14 @@ retry() {
...
+yarn run http-server public --port $HTTP_SERVER_PORT &>/dev/null &
+HTTP_SERVER_PID=$!
+
+# Run the link checker once the HTTP server is listening.
+while ! nc -z localhost $HTTP_SERVER_PORT; do sleep 0.1; done
+# Re-run the link checker up to three times, to handle the occasional transient failure.
 retry check_links
+
+# Kill the server process.
+kill -f $HTTP_SERVER_PID
```
Comment (justinvp) [inline scripts/check-links.sh]: Is the `-f` flag needed for `kill`?

Comment (cnunciato) [reply scripts/check-links.sh]: Ah, no, my oversight -- it isn't. I'll remove it.
